import {StyleSheet, Dimensions} from 'react-native';

export const styles = StyleSheet.create({
  root: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  body: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  safeContainer: {
    width: '100%',
    flexGrow: 1,
  },
  fabContainer: {
    width: 56,
    height: 56,
    position: 'absolute',
    right: 16,
    bottom: 16,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#abc123',
    borderRadius: 28,
    overflow: 'hidden',
  },
  fabButton: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContentContainer: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 2,
  },
  todoContainer: {
    width: Dimensions.get('screen').width,
    height: 48,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: '#888888',
  },
  deleteContainer: {
    width: 24,
    height: 24,
    position: 'absolute',
    right: 0,
    marginRight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButton: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
});
